region            = "us-east-1"
ami               = "ami-ed7f7296"
server_instance_type = "t2.medium"
client_instance_type = "t2.medium"
key_name          = "vagrant"
server_count      = "1"
client_count      = "2"
cluster_tag_value = "auto-join"
